
spring:
  application:
    name: Products-Service

  data:
    mongodb:
      host: ds245210.mlab.com
      port: 45210
      database: nawaz
      username: nawaz
      password: Nawaz@123

#mongodb://<dbuser>:<dbpassword>@ds245210.mlab.com:45210/nawaz